name: Upload artifact
on:
  push:
    branches: [ test ]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v4
      with:
        name: test-artifact
        path: test/dist/artifact
        overwrite: true

  Download:
    runs-on: ubuntu-latest
    needs: Upload
    steps:
    - run: ls -lR .
    - uses: actions/download-artifact@v4
      with:
        name: test-artifact
    - run: ls -lR .
    - run: cat artifact