name: Upload artifact
on:
  push:
    branches: [ main ]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: license
        path: LICENSE
