name: Upload artifact
on:
  push:
    branches: [ main ]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: artifact
    - name: Notify download
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.DOWNLOAD_WORKFLOW_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: '${{ github.repository_owner }}',
            repo: 'download-artifact',
            workflow_id: 'download.yaml',
            ref: 'main',
            inputs: {
              run_id: '${{ github.run_id }}'
            }
          });
